### ISSUE TITLE
Log4Net Appender does not send to Airbrake due to security protocols

### ISSUE THREAD

**Issue by jdsink** [airbrake/sharpbrake#107]
When testing with the log4net appender, I noticed errors never arrived within Airbrake unless I was using Fiddler to proxy the commands.  After some digging through SharpBrake I noticed that the NotifyAsync would fail with log4net with the following message "The request was aborted: Could not create SSL/TLS secure channel.".

It seams the NotifyAsync method isn't capable of negotiating a security protocol when the log4net appender is being used.  Building a AirbrakeNotifier using only the SharpBrake.Client and sending a single message does work.

To work around this issue I am currently running a custom copy of SharpBrake.Client where NotifyAsync negotiates the security protocol.

ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;

**Comment by rbalabukh** [comment]
This is not an issue of Sharpbrake. The issue is because Tls 1.2 is not enabled in .net by default. You can enable it for your application. The problem is that there is only global setting for all application. So this is not good to make changes in SharpBrake.Client.
https://github.com/airbrake/sharpbrake/issues/95
https://stackoverflow.com/questions/28286086/default-securityprotocol-in-net-4-5

**Comment by jdsink** [comment]
The SharpBrake.Client works fine by itself if you use NotifyAsync and modify my project to use only the client.  The issue is when you use the Log4net appender.  In theory, if I have a software project I should be able to add a new appender to log4net without any code changes (ie only a log4net.config change).   Today, the appender doesn't allow that.
