### ISSUE TITLE
System.MissingMethodException during SendToAirbrake after installation of package

### ISSUE THREAD

**Issue by Yezior** [airbrake/sharpbrake#28]
Hi

After creating account, I installed Sharpbrake package in newly created asp .net web forms projects (vs 2013, .net 4.5), set appsettings in web.config and tried send exception to aibrake (method SendToAirbrake) and had this exception:

```
An exception of type 'System.MissingMethodException' occurred in SharpBrake.dll but was not handled in user code

Additional information: Method not found: 'Common.Logging.ILog Common.Logging.LogManager.GetLogger(System.Type)'.
```

Log from installing package:

PM> Install-Package SharpBrake
Attempting to resolve dependency 'Common.Logging'.
Attempting to resolve dependency 'Common.Logging.Core (≥ 3.0.0)'.
Installing 'Common.Logging.Core 3.0.0'.
Successfully installed 'Common.Logging.Core 3.0.0'.
Installing 'Common.Logging 3.0.0'.
Successfully installed 'Common.Logging 3.0.0'.
Installing 'SharpBrake 2.2.1'.
Successfully installed 'SharpBrake 2.2.1'.
Adding 'Common.Logging.Core 3.0.0' to AirbrakeTest.
Successfully added 'Common.Logging.Core 3.0.0' to AirbrakeTest.
Adding 'Common.Logging 3.0.0' to AirbrakeTest.
Successfully added 'Common.Logging 3.0.0' to AirbrakeTest.
Adding 'SharpBrake 2.2.1' to AirbrakeTest.

Successfully added 'SharpBrake 2.2.1' to AirbrakeTest.

My code:

```
public partial class About : Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
        }

        protected void CrashButton_Clicked(object sender, EventArgs e)
        {
            try
            {
                throw new Exception("Our app crashed! " + Guid.NewGuid());
            }
            catch (Exception exception)
            {
                // Oh noes!
                exception.SendToAirbrake();
            }
        }
    }
```

Can someone help with this?

**Comment by patrickgreene** [comment]
I've had the same problem and here is what I've found in the GitHub project for Common.Logging (https://github.com/net-commons/common-logging/issues/74)

"Under Common.Logging 3.0, the interface ILog is actually not in the Common.Logging assembly so your specific error is probably to be expected. Under Common.Logging 3.0 the ILog interface was moved to the Common.Logging.Core assembly."

It seems like the problem is SharpBrake was using a version of Common.Logging prior to 3.0 and the later version of Common.Logging deprecated a method. From other threads, it looks like this change broke a few other projects as well - Couchbase, Log4Net, etc.

The Sharbrake NuGet packaging cannot be used since each NuGet update of Sharpbrake brings in the incompatible 3.0 versions of Common.Logging and breaks the solution again each time. The only fix our team could come up with was to compile and reference standalone instances of Sharpbrake, Common.Logging, and Common.Logging.Core (we used a prior version 2.3.1); but at this point we have stopped using Sharpbrake (and Airbrake) altogether because we do not want to maintain independent versions of each DLL.

**Comment by Yezior** [comment]
Thanks for explaining :+1:

**Comment by patrickgreene** [comment]
Also, our "hack" solution to get it working and verify that Airbrake was receiving errors was to un-install the SharpBrake package completely and re-install all three packages individually with the Package Manager Console (in this order):
1. Install Common.Logging.Core version 2.2.1 - (run: PM> Install-Package Common.Logging.Core -Version 2.2.1 )
2. Install Common.Logging version 2.3.1 - (run: PM> Install-Package Common.Logging -Version 2.3.1)
3. Install SharpBrake (latest version) - (run: PM> Install-Package SharpBrake)

Then we added the following to our web.config
<add key="Airbrake.ApiKey" value="[your API key]" />
<add key="Airbrake.Environment" value="[any string]" />
Note that we did NOT set a server URI key, we had to let SharpBrake use its default.

Then we added our SharpBrake using statement and a method call code to our Try/Catch block:

try
{ // some code }

catch (Exception ex)
{ 
     Extensions.SendToAirbrake(ex); 
} 

Everything worked; but we can't be certain it will continue to work over time and we can never drop everything and add SharpBrake back directly through NuGet or it will break again.

**Comment by Yezior** [comment]
Nice trick :) However I left checking how airbrake works, since there was this issue and because I found bugsnag which better suits our needs. Again, thanks for answer :+1:

**Comment by hbarrington** [comment]
We are also experiencing this issue. How difficult would it be to update the Nuget and use the correct/more modern logging library? We were planning on using Airbrake but will probably switch if this isn't resolved quickly :disappointed:

**Comment by aholovko** [comment]
It should not be a case anymore with new [Sharpbrake](https://github.com/airbrake/sharpbrake#key-features). Please refer to [NuGet](https://github.com/airbrake/sharpbrake#nuget) for updated packages. If you are still experienced any problem, please open a new issue so we can resolve it as soon as possible. Thanks for your interest in our notifier.
