### ISSUE TITLE
Getting Inner Exception details

### ISSUE THREAD

**Issue by raviroyind** [airbrake/sharpbrake#33]
Hi, I have been using airbreak to trap all exceptions in my application.
One thing I have noticed that the error messages displayed are very generic  in nature.

For example:

> File  Invoice.BLL.APIHelper:120
> Hostname  DESKTOP-DMZ99
> Error type    System.NullReferenceException
> Error message NullReferenceException: Object reference not set to an instance of an object.
> Where Invoice.BLL.APIHelper

This does not gives details of Inner exception which I know is not null.
Is there a configuration setting by which I can get the inner exception message?

**_Warm Regards_**

**Comment by alexxsmall** [comment]
This is a must have, we need this feature too. I believe people have been requesting this since 2012 (ticket #20), are there any plans to implement this?

**Comment by nicpillinger** [comment]
deal breaker for us too, are people really using this in production without being able to see a proper stack trace?

**Comment by alexxsmall** [comment]
To preserve our stacktrace we have had to change and rewrite how we handle exceptions (which is already complex enough as it is) by creating a new type of exception and modifying within the ctor. Due to the search facility not working, we have also had to hack together even more code to prefix the search criteria (in our case, instance Id) to exception messages.

Not fun, and I thought the whole point of Airbrake was to do just this.. It's just a pretty dashboard really..

Sent from my iPhone

On 23 Aug 2016, at 16:52, Nic Pillinger <notifications@github.com<mailto:notifications@github.com>> wrote:


deal breaker for us too, are people really using this in production without being able to see a proper stack trace?

-

**Comment by nicpillinger** [comment]
@alexxsmall we use honeybadger on all our ruby stuff and have checked out raygun too - airbrake was imposed on us as a client already use it. however - airbrake is totally capable of doing this so I'm not sure what is going on? it seemse sharpbrake just isnt' passing that stuff through?

**Comment by aholovko** [comment]
Getting info on inner exceptions is supported in our new notifier. Please [try it](https://github.com/airbrake/sharpbrake#installation) and feel free to report on any issues or request new features. We are looking forward to making it better.
